config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :notes, only: [:index, :new, :create]

  root to:"application#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :password, presence: true
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def index
    @user_status = cookies[:user_status]
    begin
      @user = User.find(cookies[:user_id])
    rescue
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_login

  def index
    @notes = Note.all
  end

  def new
    @note = Note.new
  end

  def create
    Note.create(body: params[:note][:body])
    redirect_to notes_path
  end


  def require_login
    @user_status = cookies[:user_status]
    redirect_to root_path if @user_status != 'signed_in'
    @user = User.find(cookies[:user_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.password == params[:session][:password]
      cookies[:user_status] = { value: 'signed_in', expires: 1.year.from_now }
      cookies[:user_id] = { value: user.id, expires: 1.year.from_now }
      redirect_to root_path
    else
      render plain: 'No such user'
    end
  end

  def destroy
    cookies.delete :user_status
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(name: params[:user][:name], password: params[:user][:password])
    if @user.errors.empty?
      redirect_to root_path
    else
      render plain: @user.errors.messages[:name].to_s + @user.errors.messages[:password].to_s
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def signed?
    @user_status == 'signed_in'
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      Welcome to <button href=''class="btn btn-success">Friend Face!</button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FriendFace</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <ul>
    <% if !signed? %>
      <li><%= link_to 'Register', new_user_path %></li>
      <li><%= link_to 'Sign In', new_session_path %></li>
    <% else %>
      <li><%= link_to 'All notes', notes_path %></li>
      <li><%= link_to 'My notes', '#' %></li>
      <li><%= link_to 'New note', new_note_path %></li>
      <li><%= link_to 'Sign Out', session_path(1), method: :delete%></li>
    <% end %>
  </ul>
</nav>

<%= yield %>

</body>
</html>

app/views/notes/index.html.erb
<h1>All Notes</h1>

<% @notes.each do |n| %>
  <p><%= n.body %></p>
<%end%>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= form_for(@note) do |form| %>
  <%= form.label :body, 'Note' %> <br>
  <%= form.text_area :body %> <br>
  <%= form.submit "Create new note"%>
<% end %>

app/views/users/new.html.erb
<h1>Register new user</h1>

<%= form_for(@user) do |form| %>
  <%= form.label :name %> <br>
  <%= form.text_field :name %> <br>
  <%= form.label :password %> <br>
  <%= form.text_field :password %> <br>
  <%= form.submit "Create new account"%>
<% end %>